name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set execute permissions for Gradlew
      run: chmod +x gradlew
    - name: Cache Loom
      id: cache-loom
      uses: actions/cache@v4
      with:
        path: 'build/loom-cache'
        key: ${{ runner.os }}-loom
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get JAR file name
      id: get-jar-name
      run: |
        echo "JAR_FILE=$(ls build/libs/*.jar)" >> $GITHUB_OUTPUT
    - name: Build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: '${{ steps.get-jar-name.outputs.JAR_FILE }}'
